Universe   = vanilla
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
environment = "HOME=/home/cloud-user"
RunAsOwner = True

transfer_output_files = /dev/null

Executable = code_repos/canfar_scripts/cal_pipe/casa_batch_extra_calplots.bash

Log = output_files/logs/casanfar_batch_extra_calplots.log
Output = output_files/output/casanfar_batch_extra_calplots.out
Error = output_files/error/casanfar_batch_extra_calplots.err
Queue
