Universe   = vanilla
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
environment = "HOME=/home/ekoch"
RunAsOwner = True

transfer_output_files = /dev/null

Executable = code_repos/canfar_scripts/img_pipe/archival_data/single_channel_clean.bash
Arguments = 90
Log = output_files/logs/single_channel_clean_90.log
Output = output_files/output/single_channel_clean_90.out
Error = output_files/error/single_channel_clean_90.err
Queue
Arguments = 91
Log = output_files/logs/single_channel_clean_91.log
Output = output_files/output/single_channel_clean_91.out
Error = output_files/error/single_channel_clean_91.err
Queue
Arguments = 92
Log = output_files/logs/single_channel_clean_92.log
Output = output_files/output/single_channel_clean_92.out
Error = output_files/error/single_channel_clean_92.err
Queue
Arguments = 93
Log = output_files/logs/single_channel_clean_93.log
Output = output_files/output/single_channel_clean_93.out
Error = output_files/error/single_channel_clean_93.err
Queue
Arguments = 94
Log = output_files/logs/single_channel_clean_94.log
Output = output_files/output/single_channel_clean_94.out
Error = output_files/error/single_channel_clean_94.err
Queue
Arguments = 95
Log = output_files/logs/single_channel_clean_95.log
Output = output_files/output/single_channel_clean_95.out
Error = output_files/error/single_channel_clean_95.err
Queue
Arguments = 96
Log = output_files/logs/single_channel_clean_96.log
Output = output_files/output/single_channel_clean_96.out
Error = output_files/error/single_channel_clean_96.err
Queue
Arguments = 97
Log = output_files/logs/single_channel_clean_97.log
Output = output_files/output/single_channel_clean_97.out
Error = output_files/error/single_channel_clean_97.err
Queue
Arguments = 98
Log = output_files/logs/single_channel_clean_98.log
Output = output_files/output/single_channel_clean_98.out
Error = output_files/error/single_channel_clean_98.err
Queue
Arguments = 99
Log = output_files/logs/single_channel_clean_99.log
Output = output_files/output/single_channel_clean_99.out
Error = output_files/error/single_channel_clean_99.err
Queue
