Universe   = vanilla
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
environment = "HOME=/home/ekoch"
RunAsOwner = True
next_job_start_delay=120

transfer_output_files = /dev/null


Executable = code_repos/canfar_scripts/img_pipe/archival_data/single_channel_clean.bash
Arguments = 80
Log = output_files/logs/single_channel_clean_80.log
Output = output_files/output/single_channel_clean_80.out
Error = output_files/error/single_channel_clean_80.err
Queue
Arguments = 81
Log = output_files/logs/single_channel_clean_81.log
Output = output_files/output/single_channel_clean_81.out
Error = output_files/error/single_channel_clean_81.err
Queue
Arguments = 82
Log = output_files/logs/single_channel_clean_82.log
Output = output_files/output/single_channel_clean_82.out
Error = output_files/error/single_channel_clean_82.err
Queue
Arguments = 83
Log = output_files/logs/single_channel_clean_83.log
Output = output_files/output/single_channel_clean_83.out
Error = output_files/error/single_channel_clean_83.err
Queue
Arguments = 84
Log = output_files/logs/single_channel_clean_84.log
Output = output_files/output/single_channel_clean_84.out
Error = output_files/error/single_channel_clean_84.err
Queue
Arguments = 85
Log = output_files/logs/single_channel_clean_85.log
Output = output_files/output/single_channel_clean_85.out
Error = output_files/error/single_channel_clean_85.err
Queue
Arguments = 86
Log = output_files/logs/single_channel_clean_86.log
Output = output_files/output/single_channel_clean_86.out
Error = output_files/error/single_channel_clean_86.err
Queue
Arguments = 87
Log = output_files/logs/single_channel_clean_87.log
Output = output_files/output/single_channel_clean_87.out
Error = output_files/error/single_channel_clean_87.err
Queue
Arguments = 88
Log = output_files/logs/single_channel_clean_88.log
Output = output_files/output/single_channel_clean_88.out
Error = output_files/error/single_channel_clean_88.err
Queue
Arguments = 89
Log = output_files/logs/single_channel_clean_89.log
Output = output_files/output/single_channel_clean_89.out
Error = output_files/error/single_channel_clean_89.err
Queue
Arguments = 90
Log = output_files/logs/single_channel_clean_90.log
Output = output_files/output/single_channel_clean_90.out
Error = output_files/error/single_channel_clean_90.err
Queue
Arguments = 91
Log = output_files/logs/single_channel_clean_91.log
Output = output_files/output/single_channel_clean_91.out
Error = output_files/error/single_channel_clean_91.err
Queue
Arguments = 92
Log = output_files/logs/single_channel_clean_92.log
Output = output_files/output/single_channel_clean_92.out
Error = output_files/error/single_channel_clean_92.err
Queue
Arguments = 93
Log = output_files/logs/single_channel_clean_93.log
Output = output_files/output/single_channel_clean_93.out
Error = output_files/error/single_channel_clean_93.err
Queue
Arguments = 94
Log = output_files/logs/single_channel_clean_94.log
Output = output_files/output/single_channel_clean_94.out
Error = output_files/error/single_channel_clean_94.err
Queue
Arguments = 95
Log = output_files/logs/single_channel_clean_95.log
Output = output_files/output/single_channel_clean_95.out
Error = output_files/error/single_channel_clean_95.err
Queue
Arguments = 96
Log = output_files/logs/single_channel_clean_96.log
Output = output_files/output/single_channel_clean_96.out
Error = output_files/error/single_channel_clean_96.err
Queue
Arguments = 97
Log = output_files/logs/single_channel_clean_97.log
Output = output_files/output/single_channel_clean_97.out
Error = output_files/error/single_channel_clean_97.err
Queue
Arguments = 98
Log = output_files/logs/single_channel_clean_98.log
Output = output_files/output/single_channel_clean_98.out
Error = output_files/error/single_channel_clean_98.err
Queue
Arguments = 99
Log = output_files/logs/single_channel_clean_99.log
Output = output_files/output/single_channel_clean_99.out
Error = output_files/error/single_channel_clean_99.err
Queue
Arguments = 100
Log = output_files/logs/single_channel_clean_100.log
Output = output_files/output/single_channel_clean_100.out
Error = output_files/error/single_channel_clean_100.err
Queue
