Universe   = vanilla
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
environment = "HOME=/home/ekoch"
RunAsOwner = True
next_job_start_delay=120

transfer_output_files = /dev/null


Executable = code_repos/canfar_scripts/img_pipe/archival_data/single_channel_clean.bash
Arguments = 123
Log = output_files/logs/single_channel_clean_123.log
Output = output_files/output/single_channel_clean_123.out
Error = output_files/error/single_channel_clean_123.err
Queue
