Universe   = vanilla
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
environment = "HOME=/home/ekoch"
RunAsOwner = True

transfer_output_files = /dev/null

request_memory = 8 G
request_cpus = 2

Executable = code_repos/canfar_scripts/img_pipe/archival_data/single_channel_clean.bash
Arguments = 146
Log = output_files/logs/single_channel_clean_146.log
Output = output_files/output/single_channel_clean_146.out
Error = output_files/error/single_channel_clean_146.err
Queue
