Universe   = vanilla
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
environment = "HOME=/home/ekoch"
RunAsOwner = True
notify_user = koch.eric.w@gmail.com
notification = Always

transfer_output_files = /dev/null

Executable = code_repos/canfar_scripts/split/casanfar_split_batch.bash

Arguments = 14B-088_20141116_1416220528659, 14B-088.sb29812125.eb29989958.56978.238293993054
Log = output_files/logs/split_20141116_1416220528659.log
Output = output_files/output/split_20141116_1416220528659.out
Error = output_files/error/split_20141116_1416220528659.err
Queue